import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import packageJson from "../../package.json";
import { Analytics } from "@vercel/analytics/next";
import Navbar from "@/components/Navbar";
import MobileNavigation from "@/components/MobileNavigation";
import ScrollToTop from "@/components/ScrollToTop";
import Footer from "@/components/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const version = packageJson?.version ?? "1.0.0";
    const recaptchaSiteKey = process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY;

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Navbar />
                <MobileNavigation />
                {children}
                <Footer version={version} />
                <ScrollToTop />
                <Analytics />

                {/* Google reCAPTCHA v3 Script */}
                {recaptchaSiteKey && (
                    <Script
                        src={`https://www.google.com/recaptcha/api.js?render=${recaptchaSiteKey}`}
                        strategy="lazyOnload"
                    />
                )}
            </body>
        </html>
    );
}
